#!/bin/bash
# ~/bin/bin/mob-startup

mkdir -p "$HOME/.mob-state"

echo "[$(date '+%F %T')] Starting up"

# -- Reset browser --
HELIUM_BUNDLE=$(defaults read "/Applications/Helium.app/Contents/Info" CFBundleIdentifier)
rm -rf "$HOME/Library/Application Support/$HELIUM_BUNDLE"
cp -r ~/.mob-state/helium "$HOME/Library/Application Support/$HELIUM_BUNDLE"

echo "[$(date '+%F %T')] Browser reset"

# -- Revoke credentials --
gh auth logout --hostname github.com
rm -rf ~/.config/gh

gcloud auth revoke --all
rm -rf ~/.config/gcloud

slack logout --all

echo "[$(date '+%F %T')] Credentials revoked"

# -- Remove code
rm -rf ~/code/

echo "[$(date '+%F %T')] Source code removed"

# -- Clear day state --
rm -rf ~/Library/Saved\ Application\ State/*
rm -f ~/.mob-state/authenticated-*

echo "[$(date '+%F %T')] Day state cleared"

# -- Shutdown --
echo "⭐ Station reset and ready..."
